#!/usr/bin/env python3

# Copyright 2026 The kbind Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate or update source-file boilerplate headers from templates."""

import argparse
import datetime
import glob
import os
import re
import sys


YEAR_RE = re.compile(r"\b\d{4}(?:-\d{4})?\b")
COPYRIGHT_RE = re.compile(
    r"Copyright\s+(\d{4})(?:-(\d{4}))?\s+The kbind Authors\."
)


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "filenames",
        help="list of files to update, all files if unspecified",
        nargs='*')

    rootdir = os.path.abspath('.')
    parser.add_argument("--rootdir",
                        default=rootdir,
                        help="root directory to examine")

    default_boilerplate_dir = os.path.join(rootdir, "hack/boilerplate")
    parser.add_argument("--boilerplate-dir", default=default_boilerplate_dir)

    parser.add_argument(
        '--skip',
        default=[
            'external/bazel_tools',
            '.git',
            'node_modules',
            '_output',
            'third_party',
            'vendor',
            'verify/boilerplate/test',
            'verify_boilerplate.py',
            'generate_boilerplate.py',
        ],
        action='append',
        help='Customize paths to avoid',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Report files that would be changed without writing them',
    )
    return parser.parse_args()


def get_refs():
    refs = {}

    template_dir = ARGS.boilerplate_dir
    if not os.path.isdir(template_dir):
        template_dir = os.path.dirname(template_dir)
    for path in glob.glob(os.path.join(template_dir, "boilerplate.*.txt")):
        extension = os.path.basename(path).split(".")[1]

        with open(path, 'r', encoding='utf-8') as ref_file:
            refs[extension] = ref_file.read().splitlines()

    return refs


def file_extension(filename):
    return os.path.splitext(filename)[1].split(".")[-1].lower()


def has_ignored_header(pathname):
    with open(pathname, 'r', encoding='utf-8') as myfile:
        data = myfile.read()
        return data.startswith('// Code generated by go-bindata.')


def normalize_files(files):
    newfiles = []
    for pathname in files:
        if any(x in pathname for x in ARGS.skip):
            continue
        newfiles.append(pathname)
    for idx, pathname in enumerate(newfiles):
        if not os.path.isabs(pathname):
            newfiles[idx] = os.path.join(ARGS.rootdir, pathname)
    return newfiles


def get_files(extensions):
    files = []
    if ARGS.filenames:
        files = ARGS.filenames
    else:
        for root, dirs, walkfiles in os.walk(ARGS.rootdir):
            for dpath in ARGS.skip:
                if dpath in dirs:
                    dirs.remove(dpath)

            for name in walkfiles:
                files.append(os.path.join(root, name))

    files = normalize_files(files)
    outfiles = []
    for pathname in files:
        basename = os.path.basename(pathname)
        extension = file_extension(pathname)
        if extension in extensions or basename in extensions:
            if not has_ignored_header(pathname):
                outfiles.append(pathname)
    return outfiles


def get_year():
    return datetime.datetime.now().year


def get_year_text(header_lines, current_year):
    for line in header_lines:
        match = COPYRIGHT_RE.search(line)
        if match is None:
            continue

        start_year = match.group(1)
        end_year = match.group(2)
        if end_year is None:
            if int(start_year) == current_year:
                return start_year
            return f"{start_year}-{current_year}"

        if int(end_year) == current_year:
            return f"{start_year}-{end_year}"
        return f"{start_year}-{current_year}"

    return str(current_year)


def replace_years(lines, year_text):
    return [YEAR_RE.sub(year_text, line) for line in lines]


def render_template(lines, year_text):
    return [line.replace("YEAR", year_text) for line in lines]


def extract_prefix(lines, extension):
    prefix = []
    idx = 0

    if extension == "go":
        while idx < len(lines) and (lines[idx].startswith("//go:build") or
                                    lines[idx].startswith("// +build")):
            prefix.append(lines[idx])
            idx += 1
        if idx < len(lines) and lines[idx] == "":
            prefix.append(lines[idx])
            idx += 1
        return prefix, lines[idx:]

    if extension in ("sh", "py") and lines and lines[0].startswith("#!"):
        prefix.append(lines[0])
        idx = 1
        if idx < len(lines) and lines[idx] == "":
            prefix.append(lines[idx])
            idx += 1
        return prefix, lines[idx:]

    return prefix, lines


def update_file(pathname, refs, current_year):
    with open(pathname, 'r', encoding='utf-8') as fp:
        original = fp.read()

    if not original:
        return False

    lines = original.splitlines()
    trailing_newline = original.endswith("\n")

    basename = os.path.basename(pathname)
    extension = file_extension(pathname)
    if extension != "":
        template = refs[extension]
    else:
        template = refs[basename]

    prefix, body = extract_prefix(lines, extension)
    existing = body[:len(template)]
    normalized_existing = replace_years(existing, "YEAR")
    has_header = normalized_existing == template

    if has_header:
        year_text = get_year_text(existing, current_year)
        rest = body[len(template):]
    else:
        year_text = str(current_year)
        rest = body

    updated = prefix + render_template(template, year_text) + rest
    new_text = "\n".join(updated)
    if trailing_newline:
        new_text += "\n"

    if new_text == original:
        return False

    if ARGS.check:
        return True

    with open(pathname, 'w', encoding='utf-8') as fp:
        fp.write(new_text)
    return True


def main():
    refs = get_refs()
    filenames = get_files(refs.keys())
    current_year = get_year()

    changed = []
    for filename in sorted(filenames):
        if update_file(filename, refs, current_year):
            changed.append(filename)

    if changed and ARGS.check:
        print('%d files would be updated:' % len(changed))
        for fp in changed:
            print(os.path.relpath(fp, ARGS.rootdir))
        sys.exit(1)


if __name__ == "__main__":
    ARGS = get_args()
    main()
